site_name: Unit 20 Assignment 2
site_url: https://unit-20-assignment-2-wiki.pages.dev/

theme:
  name: material

extra_css:
  - ./style.css

repo_url: https://github.com/CharlieS-432737/Unit-20-Assignment-2-Wiki
repo_name: Unit 20 Assignment 2 Wiki

nav:
  - Introduction: "index.md"
  - Network code of practice: "Network code of practice.md"
  - Service level agreement proposal: "Service-level-agreement-proposal.md"
  - System and network requirements: "System and network requirements.md"
  - Backup procedures: 'Backup procedures/Backups and restoring procedures.md'
  - Evaluation & Justification of plans: "Evaluation and Justification of plans.md"
  - FeedBack: "FeedBack.md"
  - Support:
    - User support documentation: 'Support/User support documentation.md'
    - Proving technical support: 'Support/Proving technical support.md'
    - Escalation procedures: 'Support/Escalation procedures.md'
    - Support database: 'Support/Support database.md'
  - Security:
    - Access control: 'Security/Access control.md'
    - Security policies: 'Security/Security policies.md'
    - Traffic management: 'Security/Traffic-management.md'
  - Contingency plans:
    - Natural disasters: 'Contingency plans/Natural disasters.md'
    - Network failure: 'Contingency plans/Network failure.md'
    - Power outages: 'Contingency plans/Power outages.md'
    - Security breach: 'Contingency plans/Security breach.md'
    - Server hardware failure: 'Contingency plans/Server hardware failure.md'
    - Virus infection: 'Contingency plans/Virus infection.md'
  - Mock-Up System:
    - Support tasks: "Mock-Up system/Tasks/Support tasks.md"
    - Evidence: "Mock-Up system/Evidence of system.md"
    - Planning:
      - Test plan: "Mock-Up system/Planning/Test plan.md"
      - Network plan: 'Mock-Up system/Planning/Networking plan.md'
      - Machine setup: 'Mock-Up system/Planning/Machine setup plan.md'
      - Software: 'Mock-Up system/Planning/Software plan.md'